### ISSUE TITLE
test failures on PowerPC ppc64le 

### ISSUE THREAD

**Issue by aishwaryabk** [adamchainz/treepoem#215]
I am trying to build treepoem on rhel 7.6 ppc64le. The build passes, however there are 3 test failures:

ERRORS:
`FAILED tests/test_treepoem.py::test_barcode[interleaved2of5-0123456789] - assert (2, 1, 195, 145) is None`
`FAILED tests/test_treepoem.py::test_barcode[code128-This is code128 barcode.] - assert (4, 1, 593, 145) is None`
`FAILED tests/test_treepoem.py::test_barcode[code39-THIS IS CODE39 BARCODE.] - assert (2, 1, 795, 145) is None`

Python version:   Python 3.6.3
Environment :    Rhel 7.6 ppc64le
Pip:    pip 20.0.2 from /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pip (python 3.6)
Ghostscript 9.07

Would like some help on this issue. I am running it on a High end VM with good connectivity.

**Comment by adamchainz** [comment]
We don't do much on top of ghostscript + bwipp. Can you check how ghostscript is working, and ghostscript's compatibility?

**Comment by aishwaryabk** [comment]
@adamchainz  ghostscript seems to be running fine. I had to run ` export GS_DEVICE=display`

`bash-4.2# gs`
`GPL Ghostscript 9.07 (2013-02-14)`
`Copyright (C) 2012 Artifex Software, Inc.  All rights reserved.`
`This software comes with NO WARRANTY: see the file PUBLIC for details.`
`GS>`

**Comment by adamchainz** [comment]
Please upgrade to a new ghostscript for the tests. Barcode generation changed a bit with "smearing" on newer versions. Never really got to the bottom of it, not sure if newer ghostscript versions are actually correct now. See this still open issue: #124.

If you can figure anything else, please update, perhaps with a new issue referring to #124. Closing this because I suspect it's entirely to do with ghostscript version and not powerpc-ness. Thanks!
