### ISSUE TITLE
Not able to find barcode.ps'

### ISSUE THREAD

**Issue by HemantShrimali1982** [adamchainz/treepoem#273]
I am trying to create barcode generator with treepoem lib and it is generating also its working perfectly with python script I am using. But, when I create exe from script and try to run that script it gives following error:

Traceback (most recent call last):
  File "Barcode.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "treepoem\__init__.py", line 79, in <module>
  File "treepoem\__init__.py", line 75, in _read_file
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\HEMANT~1\\AppData\\Local\\Temp\\_MEI136082\\treepoem\\postscriptbarcode\\barcode.ps'
[3744] Failed to execute script Barcode

It is looking for barcode.ps which it is not able to find and program return error:

The script file I am using contains following code

-----------------------------------------------------------------------
import treepoem
import pyodbc
import ctypes
import os
import sys

Btype=sys.argv[1]

conn_str = (
    r"DRIVER={Microsoft Access Driver (*.mdb, *.accdb)};"
    r"DBQ=C:\Users\Hemant Shrimali\source\repos\Barcode Generator\Barcode Generator\bin\Debug\database.mdb;"
    )
cnxn = pyodbc.connect(conn_str)
crsr = cnxn.cursor()
crsr.execute("select SNO,Barcode from Barcode")

from ctypes.wintypes import MAX_PATH
dll = ctypes.windll.shell32
buf = ctypes.create_unicode_buffer(MAX_PATH + 1)
if dll.SHGetSpecialFolderPathW(None, buf, 0x0005, False):
	path=buf.value
	directory = "Barcode"
	path = os.path.join(path, directory)
	os.chdir(path)
else:
	print("Failure!")

for row in crsr.fetchall():
    image = treepoem.generate_barcode(barcode_type=Btype,data=row.Barcode,)
    image.convert("1").save(str(row.SNO)+".png")
    
crsr.close()
cnxn.close()

-----------------------------------------------------------------------

**Comment by adamchainz** [comment]
PyInstaller is not bundling the data that exists inside of the `treepoem` package. I have never used PyInstaller. You may need to configure it to bundle the data, or we might need to update `treepoem` to declare its data in a different way with e.g. pkgutils. Please can you research this? I'm sure it's a common PyInstaller issue and will have some kind of documentation.

**Comment by HemantShrimali1982** [comment]
I also used py2exe but the error remained same. or you can suggest any other lib that can build the project effectively.

**Comment by adamchainz** [comment]
It's likely we need to change something on treepoem. Please do some research in the pyinstaller/py2exe docs, I'm sure they cover it somewhere.

**Comment by adamchainz** [comment]
Closing due to lack of response.

**Comment by danieledigrandi** [comment]
Hey Adam, I'm currently facing the same error pointed out by the user who opened this request.
When I make the .exe file using pyinstaller I get the FileNotFoundError saying that in the MEI folder there is no \treepoem\postscriptbarcode\barcode.ps. Rather, inspecting the MEI folder, I can directly find the barcode.ps file, but not in the path \treepoem\postscriptbarcode. How can I solve this?

**Comment by adamchainz** [comment]
I have no idea. Did you search pyinstaller for relevant issues? Treepoem is far from the only package that bundles data.

**Comment by danieledigrandi** [comment]
Thanks for your quick response, however I tried to look into the pyinstaller documentation and similar questions, but unfortunately none of the proposed solutions worked for me. I found this https://stackoverflow.com/questions/7674790/bundling-data-files-with-pyinstaller-onefile which is a similar problem, tried all proposed solutions wrapping the bwipp_path in the load_bwipp function in __init__ file but unfortunately none of them worked. Is it possible for you to reproduce the error or when you try to make a .exe file using pyinstaller works just fine?

**Comment by adamchainz** [comment]
Yeah, I'm not going to test it for you. I don't have time for that.

**Comment by danieledigrandi** [comment]
Well, not very supportive :(
Though your library, your choices. Thanks anyway.

**Comment by adamchainz** [comment]
I had an idea of what the problem might be and made a fix in #536, just released in version 3.24.0. Please test it out.

**Comment by danieledigrandi** [comment]
Hi Adam, thanks for taking care about this request. I tried the new solution, but unfortunately pyinstaller is still not including the barcode.ps file. Narrowing down the problem, I found a workaround that partially solves the issue. In pyinstaller, you can specify two modes of generating the .exe file: --onefile and --onedir. When --onefile is used, a single .exe file is generated and pyinstaller compresses all the libraries used within the project inside this .exe, and de-compresses them in a temporary folder (usually called MEI followed by some numbers) when the program is executed. Treepoem should be inside that folder (in order then to find the barcode.ps file), but that is not the case, so probably when pyinstaller is scanning all the used libraries, for some reasons treepoem is not included. The workaround implies using --onedir rather than --onefile. In this case, pyinstaller generates a fixed folder named "_internal" that contains all the libraries used (same as the MEI folder, but this time is not temporary). Hence it is sufficient to paste the entire treepoem folder contained in the environment, in this _internal folder, and everything works. Hope this can help you if you would like to solve the issue in the future.
